package com.example.spboot.controller;

import com.example.spboot.domain.Message;
import com.example.spboot.domain.User;
import com.example.spboot.repository.MessageRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.security.core.annotation.AuthenticationPrincipal;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestParam;

import java.util.List;
import java.util.Map;

@Controller
public class MainController {

    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private MessageRepository messageRepository;


    @GetMapping("/")
    public String greeting(Map<String, Object> model) {
//        model.put("name", name);
        return "greeting";
    }

    @GetMapping("/main")
    public String main(Map<String, Object> model) {
        Iterable<Message> messages = messageRepository.findAll();

        model.put("messages", messages);
        return "main";
    }

    @PostMapping("/add")
    public String add( @AuthenticationPrincipal User user,
                       @RequestParam String text,
                       @RequestParam String tag, Map<String, Object> map){
        System.out.println(user.getUsername());

        Message message = new Message();
        message.setText(text);
        message.setTag(tag);
        message.setUser(user);

        messageRepository.save(message);

        Iterable<Message> messages = messageRepository.findAll();
        map.put("messages", messages);
        return "main";
    }

    @PostMapping("/filter")
    public String filter(@RequestParam(name = "filter") String tag, Map<String, Object> map){
        List<Message> messages = messageRepository.findByTagLike(tag);
        map.put("messages", messages);
        return "main";
    }

}
